INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Regular Fit', 'Cotton', 'US Polo', 1500.00, 'Blue', 'S', 2, 'Seller1', '010000');
						
INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Slim Fit', 'Cotton', 'US Polo', 1500.00, 'Navy Blue', 'S', 2, 'Seller2', '010001');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Regular Fit', 'Cotton', 'Lee Cooper', 1800.00, 'Navy blue', 'S', 2, 'Seller3', '010002');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Slim Fit', 'Cotton', 'Lee Cooper', 1500.00, 'White', 'S', 2, 'Seller2', '010003');
						
INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Regular Fit', 'Cotton', 'PE', 1300.00, 'Black', 'S', 3, 'Seller3', '010004');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Slim Fit', 'Cotton', 'Mufti', 1900.00, 'Blue', 'S', 3, 'Seller4', '010005');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Pant', 'Slim Fit', 'Cotton', 'US Polo', 1200.00, 'Black', 'S',4, 'Seller5', '010006');
						
INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Pant', 'Slim Fit', 'Cotton', 'Lee Cooper', 1500.00, 'blue', 'S', 3,  'Seller5', '010007');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Pant', 'Slim Fit', 'Cotton', 'Mufti', 2000.00, 'Black', 'S', 1, 'Seller6', '010008');


INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Regular Fit', 'Cotton', 'US Polo', 1500.00, 'Blue', 'M', 2, 'Seller6', '010009');
						
INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Slim Fit', 'Cotton', 'US Polo', 1500.00, 'Navy Blue', 'M', 3, 'Seller6', '010010');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Regular Fit', 'Cotton', 'Lee Cooper', 1800.00, 'Navy blue', 'M', 4, 'Seller5', '010011');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Slim Fit', 'Cotton', 'Lee Cooper', 1500.00, 'White', 'L',2, 'Seller6', '010012');
						
INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Regular Fit', 'Cotton', 'PE', 1300.00, 'Black', 'M', 2, 'Seller3', '010013');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Shirt', 'Slim Fit', 'Cotton', 'Mufti', 1900.00, 'Blue', 'L', 3, 'Seller3','010017');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Pant', 'Slim Fit', 'Cotton', 'US Polo', 1200.00, 'Black', 'L', 2, 'Seller3', '010014');
						
INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Pant', 'Slim Fit', 'Cotton', 'Lee Cooper', 1500.00, 'blue', 'M', 2, 'Seller3', '010015');

INSERT INTO PRODUCT_CATELOGUE(PRODUCT_NAME, FIT_TYPE, MATERIAL, BRAND, PRICE, COLOR, PRODUCT_SIZE, STOCK_LEFT, SELLER, PRODUCT_SKU) 
VALUES ('Pant', 'Slim Fit', 'Cotton', 'Mufti', 2000.00, 'Black', 'M',4, 'Seller3', '010016');

