CREATE TABLE PRODUCT_CATELOGUE(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(150), FIT_TYPE VARCHAR(40), MATERIAL VARCHAR(40),
BRAND VARCHAR(40), PRICE DECIMAL(10,2), COLOR VARCHAR(40), PRODUCT_SIZE VARCHAR(40), 
STOCK_LEFT INTEGER, SELLER VARCHAR(40), PRODUCT_SKU VARCHAR(40));

						